
name: 'tsql_utils_dbt_utils_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  dbt_utils_dispatch_list: ['tsql_utils', 'tsql_utils_dbt_utils_integration_tests']

models:
  dbt_utils_integration_tests:
    +as_columnstore: "{{ target.type != 'sqlserver' }}"
    +enabled: true
    cross_db_utils:
      test_split_part: &not-synapse
        +enabled: "{{ target.name != 'synapse' }}"
      # BROKEN DUE TO SYNAPSE SEED LOADING EMPTY CSV VALS AS EMPTY STRINGS
      # see: https://github.com/dbt-msft/dbt-synapse/issues/36
      test_dateadd: *not-synapse
      test_datediff: *not-synapse
      test_hash: *not-synapse
      test_last_day: *not-synapse
    materializations:
      test_insert_by_period: &disabled
        +enabled: false
    sql: # BROKEN BC MACROS ARE UNPORTED STILL
      test_generate_series: *disabled
      test_get_column_values: *disabled
      test_get_relations_by_pattern: *disabled
      test_get_relations_by_prefix_and_union: *disabled
      test_groupby: *disabled # TSQL doesn't let you group by column numbers
      test_union: *not-synapse
    web: # BROKEN DUE TO TEST DEFS
      test_url_host: *disabled
      test_url_path: *disabled
      test_urls: *disabled

seeds:

  +quote_columns: false
  dbt_utils_integration_tests:
    schema_tests:
      data_test_mutually_exclusive_ranges_no_gaps: *disabled
      data_test_mutually_exclusive_ranges_with_gaps: *disabled
    cross_db:
      data_date_trunc:
        +column_types:
          updated_at: datetime
          day: date
          month: date
      data_split_part: *not-synapse

      data_dateadd:
        +column_types:
          from_time: datetime
          result: datetime

      data_datediff:
        +column_types:
          first_date: datetime
          second_date: datetime
